version: 2
jobs:
  gcc:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make all
      - run: make test
      - run: make debug
workflows:
  version: 2
  all:
    jobs:
      - gcc
